"""Tests for meeting_notes.uploader.

boto3 is never imported for real: the fake_boto3 fixture (used from Task 4
onward) injects a fake module into sys.modules, mirroring the fake
faster_whisper pattern in tests/test_transcriber_device.py. uploader.py
imports boto3 lazily inside NoteUploader._client() precisely so this works.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from meeting_notes.uploader import (
    UploadError,
    generate_slug,
    read_share_url,
    remove_share_url,
    split_frontmatter,
    write_share_url,
)

SAMPLE_NOTE = '''---
title: "Weekly Sync"
date: 2026-07-17
time: "14:00"
duration_seconds: 1800
word_count: 4213
tags: [meeting, auto-generated]
recording_file: "rec.wav"
transcript_file: "tr.md"
---

# Weekly Sync

**Date:** July 17, 2026 at 02:00 PM
**Duration:** 30m
**Words:** 4,213

## Summary

We discussed the *roadmap*.

---

*View full transcript: Press 't' to view transcript*
*Generated by Meeting Notes v0.3.0 on 2026-07-17 at 15:00:00*
'''


@pytest.fixture
def note(tmp_path) -> Path:
    p = tmp_path / "2026-07-17-weekly-sync.md"
    p.write_text(SAMPLE_NOTE)
    return p


# --- slug -------------------------------------------------------------------

def test_slug_is_long_and_urlsafe():
    slugs = {generate_slug() for _ in range(50)}
    assert len(slugs) == 50  # no collisions in a small sample
    for slug in slugs:
        assert len(slug) >= 20  # token_urlsafe(16) -> ~22 chars
        assert all(c.isalnum() or c in "-_" for c in slug)


# --- frontmatter helpers ----------------------------------------------------

def test_split_frontmatter_roundtrip():
    fm, body = split_frontmatter(SAMPLE_NOTE)
    assert 'title: "Weekly Sync"' in fm
    assert body.lstrip().startswith("# Weekly Sync")
    # Reassembly must be lossless
    assert f"---{fm}---{body}" == SAMPLE_NOTE


def test_split_frontmatter_none_when_missing():
    fm, body = split_frontmatter("# Just a heading\n")
    assert fm is None
    assert body == "# Just a heading\n"


def test_share_url_roundtrip_preserves_everything_else(note):
    assert read_share_url(note) is None
    url = "https://notes.harrywaterman.com/n/abc123XYZ_-abc123XYZ_-"
    write_share_url(note, url)
    assert read_share_url(note) == url
    remove_share_url(note)
    assert read_share_url(note) is None
    assert note.read_text() == SAMPLE_NOTE  # byte-for-byte restore


def test_write_share_url_requires_frontmatter(tmp_path):
    bare = tmp_path / "bare.md"
    bare.write_text("# No frontmatter here\n")
    with pytest.raises(UploadError):
        write_share_url(bare, "https://example.com/n/x")


def test_remove_share_url_noop_when_absent(note):
    remove_share_url(note)  # must not raise
    assert note.read_text() == SAMPLE_NOTE


def test_write_share_url_twice_replaces_not_duplicates(note):
    write_share_url(note, "https://notes.harrywaterman.com/n/first")
    write_share_url(note, "https://notes.harrywaterman.com/n/second")
    assert note.read_text().count("share_url") == 1
    assert read_share_url(note) == "https://notes.harrywaterman.com/n/second"
    remove_share_url(note)
    assert note.read_text() == SAMPLE_NOTE
