"""Tests for meeting_notes.uploader.

boto3 is never imported for real: the fake_boto3 fixture (used from Task 4
onward) injects a fake module into sys.modules, mirroring the fake
faster_whisper pattern in tests/test_transcriber_device.py. uploader.py
imports boto3 lazily inside NoteUploader._client() precisely so this works.
"""

from __future__ import annotations

import sys
import types
from pathlib import Path

import pytest

from meeting_notes.uploader import (
    UploadError,
    generate_slug,
    read_share_url,
    remove_share_url,
    split_frontmatter,
    write_share_url,
)

SAMPLE_NOTE = '''---
title: "Weekly Sync"
date: 2026-07-17
time: "14:00"
duration_seconds: 1800
word_count: 4213
tags: [meeting, auto-generated]
recording_file: "rec.wav"
transcript_file: "tr.md"
---

# Weekly Sync

**Date:** July 17, 2026 at 02:00 PM
**Duration:** 30m
**Words:** 4,213

## Summary

We discussed the *roadmap*.

---

*View full transcript: Press 't' to view transcript*
*Generated by Meeting Notes v0.3.0 on 2026-07-17 at 15:00:00*
'''


@pytest.fixture
def note(tmp_path) -> Path:
    p = tmp_path / "2026-07-17-weekly-sync.md"
    p.write_text(SAMPLE_NOTE)
    return p


# --- slug -------------------------------------------------------------------

def test_slug_is_long_and_urlsafe():
    slugs = {generate_slug() for _ in range(50)}
    assert len(slugs) == 50  # no collisions in a small sample
    for slug in slugs:
        assert len(slug) >= 20  # token_urlsafe(16) -> ~22 chars
        assert all(c.isalnum() or c in "-_" for c in slug)


# --- frontmatter helpers ----------------------------------------------------

def test_split_frontmatter_roundtrip():
    fm, body = split_frontmatter(SAMPLE_NOTE)
    assert 'title: "Weekly Sync"' in fm
    assert body.lstrip().startswith("# Weekly Sync")
    # Reassembly must be lossless
    assert f"---{fm}---{body}" == SAMPLE_NOTE


def test_split_frontmatter_none_when_missing():
    fm, body = split_frontmatter("# Just a heading\n")
    assert fm is None
    assert body == "# Just a heading\n"


def test_share_url_roundtrip_preserves_everything_else(note):
    assert read_share_url(note) is None
    url = "https://notes.harrywaterman.com/n/abc123XYZ_-abc123XYZ_-"
    write_share_url(note, url)
    assert read_share_url(note) == url
    remove_share_url(note)
    assert read_share_url(note) is None
    assert note.read_text() == SAMPLE_NOTE  # byte-for-byte restore


def test_write_share_url_requires_frontmatter(tmp_path):
    bare = tmp_path / "bare.md"
    bare.write_text("# No frontmatter here\n")
    with pytest.raises(UploadError):
        write_share_url(bare, "https://example.com/n/x")


def test_remove_share_url_noop_when_absent(note):
    remove_share_url(note)  # must not raise
    assert note.read_text() == SAMPLE_NOTE


def test_write_share_url_twice_replaces_not_duplicates(note):
    write_share_url(note, "https://notes.harrywaterman.com/n/first")
    write_share_url(note, "https://notes.harrywaterman.com/n/second")
    assert note.read_text().count("share_url") == 1
    assert read_share_url(note) == "https://notes.harrywaterman.com/n/second"
    remove_share_url(note)
    assert note.read_text() == SAMPLE_NOTE


# --- rendering --------------------------------------------------------------

def test_render_strips_frontmatter_and_footer(note):
    from meeting_notes.uploader import render_note_html
    html = render_note_html(note)
    assert "share_url" not in html
    assert "recording_file" not in html          # no frontmatter leaked
    assert "View full transcript" not in html    # local-only footer gone
    assert "Generated by Meeting Notes" not in html


def test_render_produces_selfcontained_noindex_html(note):
    from meeting_notes.uploader import render_note_html
    html = render_note_html(note)
    assert html.startswith("<!DOCTYPE html>")
    assert '<meta name="robots" content="noindex, nofollow">' in html
    assert "<title>Weekly Sync</title>" in html
    assert "<h1>Weekly Sync</h1>" in html        # markdown converted
    assert "<em>roadmap</em>" in html
    # Self-contained: no external fetches of any kind
    assert 'src="http' not in html and 'href="http' not in html
    assert "<link" not in html and "<script" not in html


def test_render_without_frontmatter_still_works(tmp_path):
    from meeting_notes.uploader import render_note_html
    bare = tmp_path / "bare.md"
    bare.write_text("# Standalone\n\nBody text.\n")
    html = render_note_html(bare)
    assert "<h1>Standalone</h1>" in html
    assert "<title>Meeting note</title>" in html


def test_render_escapes_raw_html(tmp_path):
    from meeting_notes.uploader import render_note_html
    evil = tmp_path / "evil.md"
    evil.write_text(
        '---\ntitle: "Sneaky <img> & Co"\n---\n\n'
        '# Hi\n\n<script>alert(1)</script>\n\n<img src=x onerror=alert(1)>\n'
    )
    html = render_note_html(evil)
    assert "<script>" not in html
    assert "<img src=x" not in html
    assert "alert(1)" in html  # visible as text, not executable
    assert "<title>Sneaky &lt;img&gt; &amp; Co</title>" in html


# --- NoteUploader over a fake boto3 ----------------------------------------

class FakeS3Client:
    def __init__(self):
        self.put_calls = []
        self.delete_calls = []
        self.put_error = None
        self.delete_error = None

    def put_object(self, **kwargs):
        if self.put_error:
            raise self.put_error
        self.put_calls.append(kwargs)

    def delete_object(self, **kwargs):
        if self.delete_error:
            raise self.delete_error
        self.delete_calls.append(kwargs)


@pytest.fixture
def fake_s3(monkeypatch) -> FakeS3Client:
    """Install a fake boto3 whose client() returns a controllable S3 stub."""
    client = FakeS3Client()
    fake_mod = types.ModuleType("boto3")
    fake_mod.client = lambda *args, **kwargs: client
    monkeypatch.setitem(sys.modules, "boto3", fake_mod)
    return client


@pytest.fixture
def upload_config():
    from meeting_notes.config import AppConfig
    return AppConfig(upload_bucket="test-bucket",
                     upload_base_url="https://notes.harrywaterman.com")


def test_upload_puts_html_and_writes_frontmatter(note, fake_s3, upload_config):
    from meeting_notes.uploader import NoteUploader
    url, already = NoteUploader(upload_config).upload(note)
    assert not already
    assert len(fake_s3.put_calls) == 1
    call = fake_s3.put_calls[0]
    assert call["Bucket"] == "test-bucket"
    assert call["Key"].startswith("n/")
    assert call["ContentType"] == "text/html; charset=utf-8"
    assert b"<!DOCTYPE html>" in call["Body"]
    slug = call["Key"][len("n/"):]
    assert url == f"https://notes.harrywaterman.com/n/{slug}"
    assert read_share_url(note) == url


def test_upload_already_published_returns_existing_without_put(note, fake_s3, upload_config):
    from meeting_notes.uploader import NoteUploader
    write_share_url(note, "https://notes.harrywaterman.com/n/existing-slug")
    url, already = NoteUploader(upload_config).upload(note)
    assert already
    assert url == "https://notes.harrywaterman.com/n/existing-slug"
    assert fake_s3.put_calls == []


def test_upload_failure_leaves_note_untouched(note, fake_s3, upload_config):
    from meeting_notes.uploader import NoteUploader, UploadError
    fake_s3.put_error = RuntimeError("network down")
    with pytest.raises(UploadError):
        NoteUploader(upload_config).upload(note)
    assert read_share_url(note) is None
    assert note.read_text() == SAMPLE_NOTE


def test_unpublish_deletes_then_clears_frontmatter(note, fake_s3, upload_config):
    from meeting_notes.uploader import NoteUploader
    write_share_url(note, "https://notes.harrywaterman.com/n/doomed-slug")
    NoteUploader(upload_config).unpublish(note)
    assert fake_s3.delete_calls == [{"Bucket": "test-bucket", "Key": "n/doomed-slug"}]
    assert read_share_url(note) is None
    assert note.read_text() == SAMPLE_NOTE


def test_unpublish_failure_keeps_share_url(note, fake_s3, upload_config):
    from meeting_notes.uploader import NoteUploader, UploadError
    write_share_url(note, "https://notes.harrywaterman.com/n/sticky-slug")
    fake_s3.delete_error = RuntimeError("access denied")
    with pytest.raises(UploadError):
        NoteUploader(upload_config).unpublish(note)
    # Failed delete must leave the link recorded (still live at origin)
    assert read_share_url(note) == "https://notes.harrywaterman.com/n/sticky-slug"


def test_unpublish_tolerates_missing_key(note, fake_s3, upload_config):
    from meeting_notes.uploader import NoteUploader
    write_share_url(note, "https://notes.harrywaterman.com/n/gone-slug")
    fake_s3.delete_error = RuntimeError("An error occurred (NoSuchKey) when calling DeleteObject")
    NoteUploader(upload_config).unpublish(note)  # must not raise
    assert read_share_url(note) is None


def test_unpublish_unpublished_note_raises(note, fake_s3, upload_config):
    from meeting_notes.uploader import NoteUploader, UploadError
    with pytest.raises(UploadError):
        NoteUploader(upload_config).unpublish(note)


def test_missing_boto3_gives_install_hint(note, upload_config, monkeypatch):
    from meeting_notes.uploader import NoteUploader, UploadError
    import builtins
    real_import = builtins.__import__

    def no_boto3(name, *args, **kwargs):
        if name == "boto3":
            raise ImportError("No module named 'boto3'")
        return real_import(name, *args, **kwargs)

    monkeypatch.setattr(builtins, "__import__", no_boto3)
    monkeypatch.delitem(sys.modules, "boto3", raising=False)
    with pytest.raises(UploadError, match=r"meeting-notes\[upload\]"):
        NoteUploader(upload_config).upload(note)
