"""Publish meeting notes as unlisted HTML pages (S3+CloudFront).

The share URL for a published note lives in the note's own YAML
frontmatter (`share_url:`) — it survives renames and travels with
Obsidian exports. Frontmatter edits here must preserve every other key
and the body byte-for-byte.
"""

from __future__ import annotations

import html
import re
import secrets
from pathlib import Path
from typing import Optional

from .config import AppConfig
from .logger import get_logger

logger = get_logger(__name__)

_SHARE_URL_RE = re.compile(r'^share_url:\s*"?([^"\n]+?)"?\s*$', re.MULTILINE)


class UploadError(Exception):
    """User-presentable publish/unpublish failure."""


def generate_slug() -> str:
    """128-bit unguessable URL slug."""
    return secrets.token_urlsafe(16)


def split_frontmatter(content: str) -> tuple[Optional[str], str]:
    """Split a note into (frontmatter_inner, body).

    Returns (None, content) when there is no frontmatter. The parts
    reassemble losslessly as f"---{fm}---{body}".
    """
    if content.startswith('---'):
        parts = content.split('---', 2)
        if len(parts) >= 3:
            return parts[1], parts[2]
    return None, content


def read_share_url(note_path: Path) -> Optional[str]:
    fm, _ = split_frontmatter(note_path.read_text())
    if fm is None:
        return None
    match = _SHARE_URL_RE.search(fm)
    return match.group(1) if match else None


def write_share_url(note_path: Path, url: str) -> None:
    content = note_path.read_text()
    fm, body = split_frontmatter(content)
    if fm is None:
        raise UploadError("Note has no frontmatter — can't record share_url")
    # If a share_url line exists, replace it; otherwise append.
    if _SHARE_URL_RE.search(fm):
        new_fm = re.sub(
            r'^share_url:[^\n]*',
            f'share_url: "{url}"',
            fm,
            flags=re.MULTILINE
        )
    else:
        new_fm = fm.rstrip('\n') + f'\nshare_url: "{url}"\n'
    note_path.write_text(f"---{new_fm}---{body}")


def remove_share_url(note_path: Path) -> None:
    content = note_path.read_text()
    fm, body = split_frontmatter(content)
    if fm is None:
        return
    # Remove the whole line including its newline so surrounding lines —
    # even intentional blank ones — stay byte-identical.
    new_fm = re.sub(r'^share_url:[^\n]*\n', '', fm, flags=re.MULTILINE)
    note_path.write_text(f"---{new_fm}---{body}")


_TITLE_RE = re.compile(r'^title:\s*"?(.+?)"?\s*$', re.MULTILINE)

# Everything a page needs is inline: no external CSS/JS/fonts/images, so a
# note renders even if it's the only object anyone ever fetches.
_PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>{title}</title>
<style>
body {{ max-width: 42rem; margin: 2rem auto; padding: 0 1rem;
       font-family: Georgia, 'Times New Roman', serif;
       line-height: 1.6; color: #222; background: #fff; }}
h1, h2, h3 {{ font-family: Helvetica, Arial, sans-serif; line-height: 1.25; }}
code, pre {{ background: #f4f4f4; padding: 0.1em 0.3em; }}
a {{ color: #0645ad; }}
@media (prefers-color-scheme: dark) {{
  body {{ background: #121212; color: #ddd; }}
  code, pre {{ background: #2a2a2a; }}
  a {{ color: #8ab4f8; }}
}}
</style>
</head>
<body>
{content}
</body>
</html>
"""


def _strip_footer(body: str) -> str:
    """Drop the local-only footer NoteMaker appends to every note."""
    lines = [
        line for line in body.splitlines()
        if not line.startswith('*View full transcript')
        and not line.startswith('*Generated by Meeting Notes')
    ]
    while lines and lines[-1].strip() == '':
        lines.pop()
    if lines and lines[-1].strip() == '---':  # footer's separator rule
        lines.pop()
    return '\n'.join(lines).strip() + '\n'


def render_note_html(note_path: Path) -> str:
    """Render a note's markdown body as a standalone, noindex HTML page."""
    try:
        import markdown as md
    except ImportError:
        raise UploadError(
            "The 'markdown' package is required for publishing — "
            "run: pip install 'meeting-notes[upload]'"
        )
    fm, body = split_frontmatter(note_path.read_text())
    title = "Meeting note"
    if fm is not None:
        match = _TITLE_RE.search(fm)
        if match:
            title = match.group(1)

    # Note bodies are AI summaries of untrusted transcript text (see the
    # prompt-injection boundary note in CLAUDE.md), and this HTML is served
    # publicly. python-markdown's default behavior lets raw inline/block
    # HTML pass straight through to the output, which would make transcript
    # content like "<script>...</script>" render as live, executable markup
    # (stored XSS). Deregister the two handlers responsible for that
    # pass-through — the 'html_block' preprocessor and the 'html' inline
    # pattern — so any literal HTML in the body is instead treated as plain
    # text and entity-escaped like the rest of the content. Markdown syntax
    # (headings, emphasis, lists, tables, code, links) is untouched because
    # none of that goes through the raw-HTML path.
    converter = md.Markdown(extensions=['extra'])
    converter.preprocessors.deregister('html_block')
    converter.inlinePatterns.deregister('html')
    content = converter.convert(_strip_footer(body))
    return _PAGE_TEMPLATE.format(title=html.escape(title), content=content)


class NoteUploader:
    """Publish/unpublish a note against the configured S3 bucket."""

    def __init__(self, config: AppConfig):
        self.config = config
        self.base_url = config.upload_base_url.rstrip('/')

    def _client(self):
        try:
            import boto3  # lazy: keeps boto3 optional and out of CI
        except ImportError:
            raise UploadError(
                "boto3 not installed — run: pip install 'meeting-notes[upload]'"
            )
        return boto3.client("s3", region_name=self.config.upload_region)

    def upload(self, note_path: Path) -> tuple[str, bool]:
        """Publish. Returns (url, already_published).

        share_url is written only after a successful PUT, so a failed
        upload leaves the note byte-identical.
        """
        existing = read_share_url(note_path)
        if existing:
            return existing, True
        html = render_note_html(note_path)
        slug = generate_slug()
        client = self._client()
        try:
            client.put_object(
                Bucket=self.config.upload_bucket,
                Key=f"n/{slug}",
                Body=html.encode("utf-8"),
                ContentType="text/html; charset=utf-8",
            )
        except UploadError:
            raise
        except Exception as e:
            logger.error(f"Publish failed for {note_path.name}: {e}", exc_info=True)
            raise UploadError(f"Upload failed: {e}")
        url = f"{self.base_url}/n/{slug}"
        write_share_url(note_path, url)
        logger.info(f"Published {note_path.name} -> {url}")
        return url, False

    def unpublish(self, note_path: Path) -> str:
        """Delete from S3, then clear share_url. Returns the dead URL.

        S3 delete goes first so a failure leaves the link recorded (it is
        still live at the origin). A missing key counts as success.
        """
        url = read_share_url(note_path)
        if not url:
            raise UploadError("Note is not published")
        slug = url.rsplit('/n/', 1)[-1]
        client = self._client()
        try:
            client.delete_object(Bucket=self.config.upload_bucket, Key=f"n/{slug}")
        except Exception as e:
            if "NoSuchKey" not in str(e) and "404" not in str(e):
                logger.error(f"Unpublish failed for {note_path.name}: {e}", exc_info=True)
                raise UploadError(f"Unpublish failed: {e}")
        remove_share_url(note_path)
        logger.info(f"Unpublished {note_path.name} ({url})")
        return url
