#!/bin/bash
# Meeting Notes — GNOME integration installer.
# Idempotent: safe to re-run after moving the repo or changing the keybind.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(dirname "$SCRIPT_DIR")"
LAUNCHER="$HOME/.local/bin/meeting-notes"
AUTOSTART="$HOME/.config/autostart/meeting-notes-indicator.desktop"
KEY_PATH="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/meeting-notes/"
SCHEMA="org.gnome.settings-daemon.plugins.media-keys"

command -v gsettings >/dev/null || { echo "error: gsettings not found — is this GNOME?" >&2; exit 1; }
command -v kitty >/dev/null || { echo "error: kitty not found" >&2; exit 1; }

# 1. Launcher ---------------------------------------------------------------
mkdir -p "$(dirname "$LAUNCHER")"
cat > "$LAUNCHER" <<EOF
#!/bin/bash
# Launch Meeting Notes TUI (generated by gnome/install.sh — do not edit).
if pgrep -f "python.*run.py" >/dev/null; then
    notify-send "Meeting Notes" "Already running" -i audio-input-microphone || true
    exit 0
fi
if ! command -v kitty >/dev/null; then
    notify-send "Meeting Notes" "kitty not found — cannot launch" || true
    exit 1
fi
exec kitty --class meeting-notes --directory "$REPO" "$REPO/venv/bin/python" "$REPO/run.py"
EOF
chmod 0755 "$LAUNCHER"
echo "installed launcher: $LAUNCHER"

# 2. Keybind (Ctrl+Alt+M) ---------------------------------------------------
# Append our path to the custom-keybindings list without clobbering others.
CURRENT="$(gsettings get "$SCHEMA" custom-keybindings)"
NEW_LIST="$(/usr/bin/python3 - "$CURRENT" "$KEY_PATH" <<'PYEOF'
import ast, sys
raw, path = sys.argv[1], sys.argv[2]
raw = raw.removeprefix("@as").strip()
lst = ast.literal_eval(raw) if raw and raw != "[]" else []
if path not in lst:
    lst.append(path)
print(lst)
PYEOF
)"
gsettings set "$SCHEMA" custom-keybindings "$NEW_LIST"
gsettings set "$SCHEMA.custom-keybinding:$KEY_PATH" name "Meeting Notes"
gsettings set "$SCHEMA.custom-keybinding:$KEY_PATH" command "$LAUNCHER"
gsettings set "$SCHEMA.custom-keybinding:$KEY_PATH" binding "<Control><Alt>m"
echo "registered keybind: Ctrl+Alt+M -> $LAUNCHER"

# 3. Autostart entry for the indicator --------------------------------------
mkdir -p "$(dirname "$AUTOSTART")"
cat > "$AUTOSTART" <<EOF
[Desktop Entry]
Type=Application
Name=Meeting Notes Indicator
Comment=Recording status in the GNOME top bar
Exec=/usr/bin/python3 $REPO/gnome/meeting-notes-indicator.py
X-GNOME-Autostart-enabled=true
EOF
echo "installed autostart: $AUTOSTART"

# 4. Start the indicator now (if not already running) ------------------------
if ! pgrep -f "meeting-notes-indicator.py" >/dev/null; then
    nohup /usr/bin/python3 "$REPO/gnome/meeting-notes-indicator.py" >/dev/null 2>&1 &
    echo "started indicator (pid $!)"
else
    echo "indicator already running"
fi

echo "done."
