#!/bin/bash
# Meeting Notes — GNOME integration installer.
# Idempotent: safe to re-run after moving the repo or changing the keybind.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(dirname "$SCRIPT_DIR")"
LAUNCHER="$HOME/.local/bin/meeting-notes"
AUTOSTART="$HOME/.config/autostart/meeting-notes-indicator.desktop"
KEY_BASE="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
SCHEMA="org.gnome.settings-daemon.plugins.media-keys"

command -v gsettings >/dev/null || { echo "error: gsettings not found — is this GNOME?" >&2; exit 1; }
command -v kitty >/dev/null || { echo "error: kitty not found" >&2; exit 1; }

# 1. Launcher ---------------------------------------------------------------
mkdir -p "$(dirname "$LAUNCHER")"
cat > "$LAUNCHER" <<EOF
#!/bin/bash
# Launch/control Meeting Notes TUI (generated by gnome/install.sh — do not edit).
#
# No args        launch; if already running, start recording (SIGUSR1)
# stop           end the active recording and process it (SIGUSR2)
# cancel         discard the active recording (SIGRTMIN+1)
#
# Recording state comes from the .status file the app maintains for
# Waybar/the indicator.
case "\${1:-}" in
    stop|cancel)
        if ! pgrep -f "python.*run.py" >/dev/null; then
            notify-send "Meeting Notes" "Not running" -i audio-input-microphone || true
            exit 0
        fi
        STATUS="\$(sed -n 's/^STATUS="\\(.*\\)"/\\1/p' "$REPO/.status" 2>/dev/null)"
        if [ "\$STATUS" != "recording" ]; then
            notify-send "Meeting Notes" "No recording to \$1" -i audio-input-microphone || true
            exit 0
        fi
        if [ "\$1" = "stop" ]; then
            pkill -USR2 -f "python.*run.py" || true
            notify-send "Meeting Notes" "Recording ended — processing…" -i audio-input-microphone || true
        else
            pkill --signal RTMIN+1 -f "python.*run.py" || true
            notify-send "Meeting Notes" "Recording cancelled" -i audio-input-microphone || true
        fi
        exit 0
        ;;
esac
if pgrep -f "python.*run.py" >/dev/null; then
    STATUS="\$(sed -n 's/^STATUS="\\(.*\\)"/\\1/p' "$REPO/.status" 2>/dev/null)"
    if [ "\$STATUS" = "recording" ]; then
        notify-send "Meeting Notes" "Already recording" -i media-record || true
    else
        pkill -USR1 -f "python.*run.py" || true
        notify-send "Meeting Notes" "Recording started" -i media-record || true
    fi
    exit 0
fi
if ! command -v kitty >/dev/null; then
    notify-send "Meeting Notes" "kitty not found — cannot launch" || true
    exit 1
fi
exec kitty --class meeting-notes --directory "$REPO" "$REPO/venv/bin/python" "$REPO/run.py"
EOF
chmod 0755 "$LAUNCHER"
echo "installed launcher: $LAUNCHER"

# 2. Keybinds ---------------------------------------------------------------
# Ctrl+Alt+M launch/start, Ctrl+Alt+S end+process, Ctrl+Alt+X cancel.
# Append our paths to the custom-keybindings list without clobbering others.
CURRENT="$(gsettings get "$SCHEMA" custom-keybindings)"
NEW_LIST="$(/usr/bin/python3 - "$CURRENT" \
    "$KEY_BASE/meeting-notes/" \
    "$KEY_BASE/meeting-notes-stop/" \
    "$KEY_BASE/meeting-notes-cancel/" <<'PYEOF'
import ast, sys
raw, paths = sys.argv[1], sys.argv[2:]
raw = raw.removeprefix("@as").strip()
lst = ast.literal_eval(raw) if raw and raw != "[]" else []
for path in paths:
    if path not in lst:
        lst.append(path)
print(lst)
PYEOF
)"
gsettings set "$SCHEMA" custom-keybindings "$NEW_LIST"

register_keybind() { # <dconf path> <name> <command> <binding>
    gsettings set "$SCHEMA.custom-keybinding:$1" name "$2"
    gsettings set "$SCHEMA.custom-keybinding:$1" command "$3"
    gsettings set "$SCHEMA.custom-keybinding:$1" binding "$4"
    echo "registered keybind: $4 -> $3"
}
register_keybind "$KEY_BASE/meeting-notes/" "Meeting Notes" "$LAUNCHER" "<Control><Alt>m"
register_keybind "$KEY_BASE/meeting-notes-stop/" "Meeting Notes — end recording" "$LAUNCHER stop" "<Control><Alt>s"
register_keybind "$KEY_BASE/meeting-notes-cancel/" "Meeting Notes — cancel recording" "$LAUNCHER cancel" "<Control><Alt>x"

# 3. App entry (GNOME app grid / dash, pinnable) -----------------------------
APP_DESKTOP="$HOME/.local/share/applications/meeting-notes.desktop"
mkdir -p "$(dirname "$APP_DESKTOP")"
cat > "$APP_DESKTOP" <<EOF
[Desktop Entry]
Type=Application
Name=Meeting Notes
Comment=Record, transcribe and summarize meetings
Exec=$LAUNCHER
Icon=audio-input-microphone
Terminal=false
Categories=AudioVideo;Audio;Office;
StartupWMClass=meeting-notes
EOF
chmod 0644 "$APP_DESKTOP"
command -v update-desktop-database >/dev/null && update-desktop-database "$(dirname "$APP_DESKTOP")" || true
echo "installed app entry: $APP_DESKTOP"

# 4. Autostart entry for the indicator --------------------------------------
mkdir -p "$(dirname "$AUTOSTART")"
cat > "$AUTOSTART" <<EOF
[Desktop Entry]
Type=Application
Name=Meeting Notes Indicator
Comment=Recording status in the GNOME top bar
Exec=/usr/bin/python3 $REPO/gnome/meeting-notes-indicator.py
X-GNOME-Autostart-enabled=true
EOF
echo "installed autostart: $AUTOSTART"

# 5. Start the indicator now (if not already running) ------------------------
if ! pgrep -f "meeting-notes-indicator.py" >/dev/null; then
    nohup /usr/bin/python3 "$REPO/gnome/meeting-notes-indicator.py" >/dev/null 2>&1 &
    echo "started indicator (pid $!)"
else
    echo "indicator already running"
fi

echo "done."
